Demo:
  directives:
    # Add iiwa_thanos
      - add_model:
          name: iiwa
          file: package://drake/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf
          default_joint_positions:
              iiwa_joint_1: [0]
              iiwa_joint_2: [0]
              iiwa_joint_3: [0]
              iiwa_joint_4: [0]
              iiwa_joint_5: [0]
              iiwa_joint_6: [0]
              iiwa_joint_7: [0]
      - add_weld:
          parent: world
          child: iiwa::iiwa_link_0
      # Add finger frames
      - add_frame:
          name: kuka_link_ee_frame
          X_PF:
            base_frame: iiwa::iiwa_link_7
            translation: [0.0, 0.0, 0.035]

    # Add schunk_wsg_50
      - add_model:
          name: wsg
          file: package://manipulation/schunk_wsg_50_welded_fingers.sdf
      - add_weld:
          parent: kuka_link_ee_frame
          child: wsg::body
          X_PC:
              translation: [0, 0, 0.045]
              rotation: !Rpy { deg: [90, 0, -90]}
      - add_frame:
          name: grasp_frame
          X_PF:
            base_frame: iiwa_link_7
            translation: [0.0, 0.0, 0.165]
  model_drivers:
    iiwa: !IiwaDriver
      hand_model_name: wsg
      control_mode: position_only
    wsg: !SchunkWsgDriver {}
    