Demo:
  directives:
    # Add iiwa_thanos
      - add_model:
          name: iiwa
          file: package://drake_models/iiwa_description/sdf/iiwa7_no_collision.sdf
          default_joint_positions:
              iiwa_joint_1: [0]
              iiwa_joint_2: [0]
              iiwa_joint_3: [0]
              iiwa_joint_4: [0]
              iiwa_joint_5: [0]
              iiwa_joint_6: [0]
              iiwa_joint_7: [0]
      - add_weld:
          parent: world
          child: iiwa::base
      # Add finger frames
      - add_frame:
          name: calibration_frame # calibration frame
          X_PF:
            base_frame: iiwa::iiwa_link_ee_kuka
            rotation: !Rpy { deg: [90.0, 0.0, 90.0]} # apriltag frame relative to kuka frame
            translation: [0.0, 0.0, 0.045] #4.5cm below gamma
    # Add schunk_wsg_50
      - add_model:
          name: wsg
          file: package://manipulation/hydro/schunk_wsg_50_with_tip.sdf
      - add_weld:
          parent: iiwa::iiwa_link_7
          child: wsg::body
          X_PC:
              translation: [0, 0, 0.09]
              rotation: !Rpy { deg: [90, 0, 90]}
  model_drivers:
    iiwa: !IiwaDriver
      hand_model_name: wsg
      control_mode: position_only {}
    wsg: !SchunkWsgDriver
      
    